### ISSUE TITLE
Design a network selector

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#181]
# Issue
We need to implement different networks in the PE, but how do we let user switch it?

# Possible solution
Create a figma design with a network select UI element

**Comment by blackmirrordesigner** [comment]
Figma link:
https://www.figma.com/design/Bw2OVsNb9cRtP8QGUvV803/NETWORK-SELECTOR?node-id=0-1&t=Wo6jANtbPz0B0PR3-1

Preview:
<img width="874" alt="Screenshot 2024-07-10 at 21 05 45" src="https://github.com/pshenmic/platform-explorer/assets/91994843/2cc57fac-91eb-4d63-805f-0e985f3b2b13">

**Comment by blackmirrordesigner** [comment]
<img width="728" alt="image" src="https://github.com/pshenmic/platform-explorer/assets/91994843/262584c3-6e09-4d0f-b27c-c809f8f9a89c">
