### ISSUE TITLE
Design footer

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#182]
# Issue
PE should have a footer that contains several info like:
* PE version
* author name
* license info
* social links

# Possible solution
Create a figma design for this task

**Comment by blackmirrordesigner** [comment]
https://www.figma.com/design/4704xY3b2arIRN2DpPBiED/FOOTER?node-id=0-1&t=A2bflfk3XUKvut4T-1
<img width="800" alt="Screenshot 2024-07-10 at 19 57 24" src="https://github.com/pshenmic/platform-explorer/assets/91994843/1a1c531c-f5ae-4a9a-a2b3-31510c1d5265">

**Comment by blackmirrordesigner** [comment]
<img width="1596" alt="image" src="https://github.com/pshenmic/platform-explorer/assets/91994843/10ae40ac-5914-44d6-bb3f-b685278e85a4">
updated version
