### ISSUE TITLE
Improve specific identity page design

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#230]
# Issue

The same as https://github.com/pshenmic/platform-explorer/issues/229, we need to improve a page about specific identity

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Identity - opened identities](https://github.com/user-attachments/assets/af03cd14-c132-4300-8324-9a1a9cb10657)
![Platform Explorer - Identity - opened public keys](https://github.com/user-attachments/assets/5b199a90-3691-4efc-a113-85c00be94e06)
![Platform Explorer - Identity - one identity](https://github.com/user-attachments/assets/ecfee745-bb1b-4184-a184-4c7ea4ed800a)
![Platform Explorer - Identity - 25 identities](https://github.com/user-attachments/assets/e9e6a67d-03d4-4f32-b19f-442d141e5238)
![Platform Explorer - Identity - no identities](https://github.com/user-attachments/assets/7e08901c-32f2-46dc-81dd-0478aa117616)
Figma file: https://www.figma.com/design/L9SJVnlyd5JS8QAVaEufrs/Identity-Page?node-id=0-1&t=jqooDLXvLqoaXYK7-1

**Comment by pshenmic** [comment]
This is sick! Many thanks
