### ISSUE TITLE
Improve validators list page design

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#231]
# Issue

We need a slight improvements on the validators lists, so it will match the UX of the other pages redesigns

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Validators](https://github.com/user-attachments/assets/2f6011be-b80f-43de-8fac-2842653f203b)

Figma file: https://www.figma.com/design/H2G6wlrlInXB6yjhIcPwiJ/Validators?node-id=0-1&t=t2GBBfe7srE0LWwY-1

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Validators](https://github.com/user-attachments/assets/f9ee045c-2a3a-48e5-a725-c66337fddb2f)
Figma file: https://www.figma.com/design/H2G6wlrlInXB6yjhIcPwiJ/Validators?node-id=0-1&t=t2GBBfe7srE0LWwY-1

**Comment by blackmirrordesigner** [comment]
<img width="430" alt="Validators" src="https://github.com/user-attachments/assets/58b91c27-47e7-4e60-b458-bc18fda81c09">
mobile version

**Comment by alexeyandreevsky** [comment]
Good job!
