### ISSUE TITLE
Improve design specific validator page

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#232]
# Issue
We need a better page design for the specific validator, because it is important page for the masternode operators.

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Validator-1](https://github.com/user-attachments/assets/9e47cdda-8cc2-4ead-8273-80a7abb56c01)

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Validator](https://github.com/user-attachments/assets/236b89a5-dd14-4344-9a7a-9b42125d9d7b)
