### ISSUE TITLE
Improve transactions list page design

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#233]
# Issue
Create a design for transactions list

# Possible solution

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Tranactions](https://github.com/user-attachments/assets/57caa686-b63b-483d-a2c3-63ef2a095fca)
Figma file: https://www.figma.com/design/5FZOz4z0OJ3ulPz7yuKLGJ/Transactions?node-id=0-1&t=xKsl3DkJzePWHx4t-1

**Comment by blackmirrordesigner** [comment]
<img width="430" alt="Transactions-1" src="https://github.com/user-attachments/assets/f49968ff-f1fd-45f9-9661-814972eef0d7">
<img width="430" alt="Transactions" src="https://github.com/user-attachments/assets/882e911d-e080-44bb-90e8-e3b8e81e130c">
mobile version plus menu

**Comment by alexeyandreevsky** [comment]
Good job!
