### ISSUE TITLE
Improve data contracts page design

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#234]
# Issue
We need a better data contracts page UX where people will be checking all possible and most trending data contracts

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Data Contracts](https://github.com/user-attachments/assets/e4dc4904-8b6b-4ad2-9e4c-b93ee520940d)

Figma link: https://www.figma.com/design/tNWFUQ8PIwMRmP7QhffiO0/Data-Contracts?node-id=0-1&t=FRkoSjZMcirolYjb-1

**Comment by blackmirrordesigner** [comment]
<img width="430" alt="Platform Explorer - Identities Mobile" src="https://github.com/user-attachments/assets/08043f83-9c3c-4b04-8d5f-6bb21c3bfb67">
mobile version

**Comment by blackmirrordesigner** [comment]
<img width="430" alt="Data Contracts" src="https://github.com/user-attachments/assets/0288e80d-b782-4332-8ab2-2f1aeb65b459">
mobile version

**Comment by alexeyandreevsky** [comment]
Good job!
