### ISSUE TITLE
Improve specific transaction page

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#236]
# Issue
We need a better UX for specific transaction page, where people see transaction details and the data that is being submitted.

**Comment by blackmirrordesigner** [comment]
<img width="1600" alt="Platform Explorer - Transactions - Voting" src="https://github.com/user-attachments/assets/8e7f5eef-f855-41bd-a819-b17e48ea0402">
<img width="1600" alt="Platform Explorer - Transactions - Credit transfer" src="https://github.com/user-attachments/assets/399672f2-2575-462c-b0d2-ac8930cf0bab">
<img width="1600" alt="Platform Explorer - Transactions - Credit Withdrawal" src="https://github.com/user-attachments/assets/e3d4c625-feb5-45c4-8d3b-91ba52015630">
<img width="1600" alt="Platform Explorer - Transactions - Identity Top-Up" src="https://github.com/user-attachments/assets/76fa4725-1bd8-42aa-b765-02e2d97544ad">
<img width="1600" alt="Platform Explorer - Transactions - Data Contract Update" src="https://github.com/user-attachments/assets/63fe5665-09dd-44a6-b32b-b61f330e4c9a">
<img width="1754" alt="Platform Explorer - Transactions - Data Contract Create" src="https://github.com/user-attachments/assets/76d22fcf-37bf-44df-a216-3e50f4764447">
<img width="1600" alt="Platform Explorer - Transactions - Documents Batch" src="https://github.com/user-attachments/assets/dcb2d2ce-3c6a-4e6b-8971-fefd3e6550ce">
<img width="1600" alt="Platform Explorer - Transactions - Identity Create (fee multiplier)" src="https://github.com/user-attachments/assets/223935a4-ea68-452d-b8dc-87dace514b7d">
<img width="1600" alt="Platform Explorer - Transactions - Identity Create" src="https://github.com/user-attachments/assets/2c1ce50a-b21d-4917-b2a7-d9c3810891aa">
<img width="1600" alt="Platform Explorer - Transactions - Identity Update" src="https://github.com/user-attachments/assets/738f1567-8580-417a-92a0-bfcf0fd66d94">
Figma Link: https://www.figma.com/design/9A5arukJnZzcSIVOaMv8Sa/Specific-Transaction-Page?node-id=0-1&t=EUKorIIETE1THCIq-1
