### ISSUE TITLE
Create design for withdrawals tab on Validator page

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#304]
# Issue

How should we show withdrawals for the users in the validator page? I think it should have some status and withdrawal document reference!

# Possible solution

**Comment by blackmirrordesigner** [comment]
![Uploading Platform Explorer - Validator - withdrawals.png…]()
Figma link: https://www.figma.com/design/KqXjiVRyKtYUkJt3Hlvv9G/Validators-Withdrawals?node-id=0-1&t=poHqjkK5n3ngrp44-1

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Validator - withdrawals](https://github.com/user-attachments/assets/565b0755-85b8-4da1-940a-f01ebb12df85)
Figma link: https://www.figma.com/design/KqXjiVRyKtYUkJt3Hlvv9G/Validators-Withdrawals?node-id=0-1&t=poHqjkK5n3ngrp44-1
