### ISSUE TITLE
Design better search

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#324]
# Issue
Right now, we have pretty small search, and its hard to work with it, as it does not return you a pre-search result

# Possible solution
Design a search, that can show off results straight in the search bar

Please all possible cases, including:
* Identity by identifier or name
* Data Contract names
* Contesting names

**Comment by blackmirrordesigner** [comment]
![search opened - 4 identities found](https://github.com/user-attachments/assets/7a98e918-519c-490d-a866-8c7081d2f4cc)
![search opened - validator IP](https://github.com/user-attachments/assets/763766a7-1f3b-40d0-a2a5-b137927e6a5d)
![search opened - one document found (id)](https://github.com/user-attachments/assets/8e0c9fc0-fc5b-4330-bc5c-2e94a908942c)
![search opened - one document found (name)](https://github.com/user-attachments/assets/a7bb686d-c0a1-4342-a419-d21f2162905f)
![search opened - 1 block found](https://github.com/user-attachments/assets/8e4e77e9-1c14-4396-bd07-8b76d615da1d)
![search opened - search opened](https://github.com/user-attachments/assets/754a9eae-2cf8-4a41-aeaa-15adfbdd475c)
![search opened - data contracts name](https://github.com/user-attachments/assets/3513adb2-4e67-4c82-aec8-850ed28e6e28)
![search opened - data contracts](https://github.com/user-attachments/assets/3ce6496a-2906-41a5-9649-ace8ed807a9f)
![search opened - searching](https://github.com/user-attachments/assets/67d0cd22-9d03-422a-8656-e8e0709746a7)
![search opened - nothing found](https://github.com/user-attachments/assets/7918aeef-8ee0-4dea-95c1-c6663e778d2a)
![search opened - 1 transaction found](https://github.com/user-attachments/assets/8a40209c-0294-4cff-bf3c-84408a1e3661)
Figma link: https://www.figma.com/design/B1Vpd3YTEs4T0ZW40AauNK/Platform-Explorer-%E2%80%94-New-Search?node-id=0-1&t=F9K8LdyHCjxtux58-1

**Comment by blackmirrordesigner** [comment]
![search opened - searching](https://github.com/user-attachments/assets/4072693c-af4a-4921-89b7-19f96c4dcd52)
Loading screen. Animated spinner.
