### ISSUE TITLE
Design filter tooltip

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#325]
# Issue
In different lists, like transactions or identities, we would like to see a toolbox that allows you to filter data in that lists, such like:

* filter by identity identifier (or name)
* filter by owner
* filter by status
* filter by gas

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Transactions - filter opened-4](https://github.com/user-attachments/assets/0f5fb0ae-29a4-40e1-b74d-0023d8d624ae)
![Platform Explorer - Transactions - filter opened-3](https://github.com/user-attachments/assets/91430549-14c7-4f6f-9a43-e432c635e980)
![Platform Explorer - Transactions - filter opened-2](https://github.com/user-attachments/assets/3b10e738-179d-4b65-8968-84674369ee20)
![Platform Explorer - Transactions - filter opened-1](https://github.com/user-attachments/assets/791284e6-b7b1-41e1-a856-c4a1ecdf0d88)
Figma link: https://www.figma.com/design/6mdlQhVqsgTPYO9QjNqOxK/Platform-Explorer-%E2%80%94-Transactions-Filter?node-id=0-1&t=V1Br1hj3q9s0ka9j-1
![Platform Explorer - Transactions - filter opened](https://github.com/user-attachments/assets/44949a94-6535-4833-98ff-9aeb6b6b5c0d)
