### ISSUE TITLE
Design identity transfers

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#339]
# Issue

Design implemented in https://github.com/pshenmic/platform-explorer/issues/230 is missing identity transfers tab

# Possible solution
Create separate tabs, liek Top Ups, Credits, Withdrawals

**Comment by blackmirrordesigner** [comment]
<img width="320" alt="Identity Info - 320" src="https://github.com/user-attachments/assets/1edaa83b-df82-4f52-8bd7-f0bc7649114f">
<img width="430" alt="Identity Info - Opened public keys" src="https://github.com/user-attachments/assets/3c2d9830-4ca0-4f19-9d9e-beb3682bf575">
<img width="430" alt="Identity Info - 430" src="https://github.com/user-attachments/assets/c35fe622-1810-49e7-b897-d2cb5c2148f1">
Figma Link: https://www.figma.com/design/pY0siExjfvQdXcQiyWIzZo/Platform-Explorer-%E2%80%94-Identity-Page-%5Bmobile%5D?node-id=0-1&t=OOOaGH9h2IG811xU-1
