### ISSUE TITLE
Design contested resources page

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#340]
# Issue

We need to create a page for viewing current and historical Masternode Votes. User should be able to see what current and finished contested resources are, and their votes

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Contested Resource - one resource](https://github.com/user-attachments/assets/398d36c1-9fb6-4233-a68d-ffcf14e9ee68)
![Platform Explorer - Contested Resource](https://github.com/user-attachments/assets/fbde8bca-591b-40ff-8273-89a93b70704a)
Figma link: https://www.figma.com/design/nfBbkDZMkXSw0jcgHRxjBc/Platform-Explorer-%E2%80%94-Contested-Resources?node-id=0-1&t=lL1Jve3qW4YNNvS3-1

**Comment by blackmirrordesigner** [comment]
![Contested Resources](https://github.com/user-attachments/assets/ea964b37-70a0-4274-8ff3-79f0ef023039)
![Platform Explorer - Contested Resource - one resource](https://github.com/user-attachments/assets/265fca32-e9ed-45de-a76f-6e4c948a8c6f)
Figma link: https://www.figma.com/design/nfBbkDZMkXSw0jcgHRxjBc/Platform-Explorer-%E2%80%94-Contested-Resources?node-id=0-1&t=lL1Jve3qW4YNNvS3-1

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Contested Resource - ended-1](https://github.com/user-attachments/assets/2089a06a-6634-4e81-a16e-375d048a9a8f)
![Platform Explorer - Contested Resource - ended](https://github.com/user-attachments/assets/0c2f7c2f-fecd-4c23-805d-69c44ca3cfa3)
![Platform Explorer - Contested Resource](https://github.com/user-attachments/assets/a6390402-9e57-4f62-8b88-92d86e45c14c)
![Contested Resources](https://github.com/user-attachments/assets/20f7e496-8979-4128-ae5c-1739c8fcec00)
Figma Link: https://www.figma.com/design/nfBbkDZMkXSw0jcgHRxjBc/Platform-Explorer-%E2%80%94-Contested-Resources?node-id=0-1&t=e2G1z68B0v9gDdk0-1

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Contested Resource - ended-1](https://github.com/user-attachments/assets/642a16af-8a6b-49d3-b83a-6eaefd1e1164)
![Platform Explorer - Contested Resource - ended](https://github.com/user-attachments/assets/c30ff2e6-c126-4785-a275-a1377868765c)
![Platform Explorer - Contested Resource](https://github.com/user-attachments/assets/38c5c315-c2d4-47fd-a3f9-17ea64d1051e)
![Contested Resources](https://github.com/user-attachments/assets/d953e8a9-13c7-4ffc-801b-9eea37a83f0d)
Small but noticeable update — the voting charts in the Contenders List

Same Figma Link: https://www.figma.com/design/nfBbkDZMkXSw0jcgHRxjBc/Platform-Explorer-%E2%80%94-Contested-Resources?node-id=0-1&t=e2G1z68B0v9gDdk0-1
