### ISSUE TITLE
Design block list page

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#341]
# Issue
We didn't have blocks lists (/blocks) redesign yet, and we just made it similar to the other pages for now, but it could be improved 

# Possible solution

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Blocks](https://github.com/user-attachments/assets/80a72c67-0bba-4685-998b-02c723f34813)
Figma link: https://www.figma.com/design/4tq7vJEKINev7GtqWRU8JO/Blocks-List?m=auto&t=s3K9oJCTBJeZYOvw-6

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Blocks](https://github.com/user-attachments/assets/1177bad1-7b25-48c0-8aef-47c3ff60883a)
Figma link: https://www.figma.com/design/4tq7vJEKINev7GtqWRU8JO/Blocks-List?m=auto&t=s3K9oJCTBJeZYOvw-6

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Blocks](https://github.com/user-attachments/assets/06046c5a-604f-4ee6-83a2-4c8442bc232b)
Figma link: https://www.figma.com/design/4tq7vJEKINev7GtqWRU8JO/Blocks-List?m=auto&t=s3K9oJCTBJeZYOvw-6
