### ISSUE TITLE
Design block details page

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#343]
# Issue
We should rework and make new design for specific blocks, where user could see info about the blocks, its transactions, info about proposer, etc.

# Possible solution

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Blocks - One opened block](https://github.com/user-attachments/assets/f6f99844-7a24-4fbe-95ee-8ea06c2b6308)
Figma link: https://www.figma.com/design/cm8Ns1PquGvWMPTxlNGu9q/Platform-Explorer-%E2%80%94-One-opened-block?m=auto&t=V3I9u8amOQJtunuw-6

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Blocks - One opened block - Quorum members](https://github.com/user-attachments/assets/2d87942d-8304-40ef-967f-406af3432535)
![Platform Explorer - Blocks - One opened block](https://github.com/user-attachments/assets/f05402c5-3c23-4bbc-b5d9-9fe90c4d700e)
Figma link: https://www.figma.com/design/cm8Ns1PquGvWMPTxlNGu9q/Platform-Explorer-%E2%80%94-One-opened-block?m=auto&t=V3I9u8amOQJtunuw-6

**Comment by pshenmic** [comment]
jzus how good it is!
