### ISSUE TITLE
Improve design specific document page

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#359]
# Issue
Specific document page is not informative rn, we haven't improved it yet, but there are a lot of detailed info that we can show.

**Comment by blackmirrordesigner** [comment]
![Platform Explorer - Document info](https://github.com/user-attachments/assets/4b520e70-9258-47aa-9c04-f33f2908f800)
Figma link: https://www.figma.com/design/08ZTSPJJ19nWUxMXzKjKAT/Platform-Explorer-%E2%80%94-Document-info?node-id=1-801&t=BaigSamAy6QLvFFv-1
