### ISSUE TITLE
Mobile version for Identity page

### ISSUE THREAD

**Issue by pshenmic** [pshenmic/platform-explorer#360]
# Issue

We haven't had a mobile view for identity page and frontend been asking how to properly show it for mobile devices

# Possible solution

**Comment by blackmirrordesigner** [comment]
<img width="320" alt="Identity Info - 320" src="https://github.com/user-attachments/assets/c94f90e6-3cad-4df0-8a37-23f6d467ad79">
<img width="430" alt="Identity Info - Opened public keys" src="https://github.com/user-attachments/assets/bd1348cb-8771-4078-a07f-62c988e51545">
<img width="430" alt="Identity Info - 430" src="https://github.com/user-attachments/assets/02f464d9-3338-45e6-a189-93000789560a">
Figma link: https://www.figma.com/design/pY0siExjfvQdXcQiyWIzZo/Platform-Explorer-%E2%80%94-Identity-Page-%5Bmobile%5D?node-id=0-1&t=OOOaGH9h2IG811xU-1
